# -*- coding: utf-8 -*-
"""LAB 1 - Intro to PyTorch and OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4tqgwAtOakkGErM7s5MTgBqoeZe3BrU
"""

import torch
from torchvision import models

resnet=models.resnet152(pretrained=True) #Load a pretrained m`odel

resnet.eval() #This is necessary so that BatchNorm values and other things do not change

from PIL import Image
img=Image.open('cats.jpg')

from torchvision import transforms
preprocess=transforms.Compose([transforms.Resize(256),
                               transforms.CenterCrop(224),
                               transforms.ToTensor(),
                               transforms.Normalize(mean=[.485,.456,.406],std=[.229,.224,.225])])

img_p=preprocess(img)
img_p.shape

img_b=torch.unsqueeze(img_p,0)
img_b.shape

output=resnet(img_b)

output.shape #Logits

value,index=torch.max(output,1) #Max logit value

from torch.nn.functional import softmax
percentages=softmax(output,dim=1)[0]*100

percentages.shape

with open('imagenet.txt') as f:
  labels=[lines.strip() for lines in f]

labels[index],percentages[index].item()

